version: '3.5'

services:
  api1: 
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    networks:
      - my-networks
    env_file: .env
    depends_on:
      - db
    expose: 
     - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    networks:
      - my-networks
    env_file: .env
    depends_on:
      - db
    expose: 
     - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'

  nginx: 
    image: nginx:latest
    networks:
      - my-networks
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'

  db: 
   image: postgres
   networks:
    - my-networks
   ports:
    - 5432:5432
   environment:
    POSTGRES_PASSWORD: example
   deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.75GB'


  cache:
   image: docker.dragonflydb.io/dragonflydb/dragonfly
   networks:
    - my-networks
   ports:
    - 6379:6379
   deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

networks:
  my-networks:
    driver: bridge